import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Navbar from "./Components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-s-primary"><main><Providers><Navbar/>{children}</Providers></main></body>
    </html>
  );
}
